/**
 * UI Event Types
 * 
 * Defines all event types emitted by the Director-Agent system to the UI.
 * Events are published to Redis Streams and consumed via SSE.
 */

// ============================================================================
// Event Categories
// ============================================================================

export type EventCategory = 
  | 'director'
  | 'scene'
  | 'evaluation'
  | 'render'
  | 'system'
  | 'agent'
  | 'preview';

// ============================================================================
// Base Event Structure
// ============================================================================

export interface BaseUIEvent {
  id: string;                    // Unique event ID (generated by Redis XADD)
  projectId: string;             // Project this event belongs to
  timestamp: number;             // Unix timestamp in milliseconds
  category: EventCategory;       // Event category for filtering
  type: string;                  // Specific event type
}

// ============================================================================
// Director Events
// ============================================================================

export interface DirectorStartedEvent extends BaseUIEvent {
  category: 'director';
  type: 'director:started';
  data: {
    totalScenes: number;
    config: Record<string, unknown>;
  };
}

export interface DirectorThinkingEvent extends BaseUIEvent {
  category: 'director';
  type: 'director:thinking';
  data: {
    thought: string;
    phase: 'planning' | 'coordinating' | 'evaluating' | 'deciding';
  };
}

export interface DirectorDecisionEvent extends BaseUIEvent {
  category: 'director';
  type: 'director:decision';
  data: {
    decision: string;
    reasoning: string;
    affectedScenes: string[];
  };
}

export interface DirectorCompletedEvent extends BaseUIEvent {
  category: 'director';
  type: 'director:completed';
  data: {
    success: boolean;
    totalDurationMs: number;
    finalScore: number;
    summary: string;
  };
}

export interface DirectorErrorEvent extends BaseUIEvent {
  category: 'director';
  type: 'director:error';
  data: {
    error: string;
    recoverable: boolean;
    phase: string;
  };
}

export type DirectorEvent = 
  | DirectorStartedEvent
  | DirectorThinkingEvent
  | DirectorDecisionEvent
  | DirectorCompletedEvent
  | DirectorErrorEvent;

// ============================================================================
// Scene Events
// ============================================================================

export interface SceneQueuedEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:queued';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
  };
}

export interface SceneGeneratingEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:generating';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
    attempt: number;
  };
}

export interface SceneGeneratedEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:generated';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
    durationMs: number;
    codeLength: number;
  };
}

export interface SceneRenderingEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:rendering';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
  };
}

export interface SceneRenderedEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:rendered';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
    durationMs: number;
    videoPath: string;
  };
}

export interface SceneErrorEvent extends BaseUIEvent {
  category: 'scene';
  type: 'scene:error';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    version: number;
    error: string;
    phase: 'generation' | 'rendering';
  };
}

export type SceneEvent = 
  | SceneQueuedEvent
  | SceneGeneratingEvent
  | SceneGeneratedEvent
  | SceneRenderingEvent
  | SceneRenderedEvent
  | SceneErrorEvent;

// ============================================================================
// Evaluation Events
// ============================================================================

export interface EvaluationStartedEvent extends BaseUIEvent {
  category: 'evaluation';
  type: 'evaluation:started';
  data: {
    tier: 1 | 2;
    sceneId?: string;         // Only for tier 1
    sceneIndex?: number;      // Only for tier 1
    sceneNumber?: number;     // Only for tier 1
    version?: number;         // Only for tier 1
  };
}

export interface EvaluationProgressEvent extends BaseUIEvent {
  category: 'evaluation';
  type: 'evaluation:progress';
  data: {
    tier: 1 | 2;
    sceneId?: string;
    step: string;
    progress: number;         // 0-100
  };
}

export interface EvaluationCompletedEvent extends BaseUIEvent {
  category: 'evaluation';
  type: 'evaluation:completed';
  data: {
    tier: 1 | 2;
    sceneId?: string;
    sceneIndex?: number;
    sceneNumber?: number;
    evaluatedVersion?: number;
    score: number;
    passed: boolean;
    feedback: string;
    details?: Record<string, number>;
  };
}

export interface EvaluationEscalatedEvent extends BaseUIEvent {
  category: 'evaluation';
  type: 'evaluation:escalated';
  data: {
    sceneId: string;
    sceneIndex: number;
    sceneNumber: number;
    reason: 'max_attempts' | 'low_score' | 'diminishing_returns';
    attempts: number;
    lastScore: number;
  };
}

export type EvaluationEvent = 
  | EvaluationStartedEvent
  | EvaluationProgressEvent
  | EvaluationCompletedEvent
  | EvaluationEscalatedEvent;

// ============================================================================
// Render Events
// ============================================================================

export interface RenderStartedEvent extends BaseUIEvent {
  category: 'render';
  type: 'render:started';
  data: {
    phase: 'scene' | 'final';
    sceneId?: string;
  };
}

export interface RenderProgressEvent extends BaseUIEvent {
  category: 'render';
  type: 'render:progress';
  data: {
    phase: 'scene' | 'final';
    sceneId?: string;
    progress: number;         // 0-100
    framesRendered: number;
    totalFrames: number;
  };
}

export interface RenderCompletedEvent extends BaseUIEvent {
  category: 'render';
  type: 'render:completed';
  data: {
    phase: 'scene' | 'final';
    sceneId?: string;
    durationMs: number;
    outputPath: string;
    fileSizeBytes: number;
  };
}

export interface RenderErrorEvent extends BaseUIEvent {
  category: 'render';
  type: 'render:error';
  data: {
    phase: 'scene' | 'final';
    sceneId?: string;
    error: string;
  };
}

export type RenderEvent = 
  | RenderStartedEvent
  | RenderProgressEvent
  | RenderCompletedEvent
  | RenderErrorEvent;

// ============================================================================
// System Events
// ============================================================================

export interface SystemHealthEvent extends BaseUIEvent {
  category: 'system';
  type: 'system:health';
  data: {
    redis: 'connected' | 'disconnected';
    queues: Record<string, number>;  // Queue name -> pending job count
    workers: Record<string, boolean>; // Worker name -> active
  };
}

export interface SystemErrorEvent extends BaseUIEvent {
  category: 'system';
  type: 'system:error';
  data: {
    error: string;
    component: string;
    fatal: boolean;
  };
}

export type SystemEvent = 
  | SystemHealthEvent
  | SystemErrorEvent;

// ============================================================================
// Agent Events (for agent hierarchy visualization)
// ============================================================================

export type AgentStatus = 
  | 'spawning'
  | 'thinking' 
  | 'generating'
  | 'rendering'
  | 'completed'
  | 'error';

export type AgentAction = 
  | 'planning'
  | 'generating_code'
  | 'validating_code'
  | 'rendering_scene'
  | 'reviewing'
  | 'refining';

export interface AgentSpawnedEvent extends BaseUIEvent {
  category: 'agent';
  type: 'agent:spawned';
  data: {
    agentId: string;
    sceneIndex: number;
    sceneName: string;
    parentAgentId?: string;  // For nested spawning (Director spawns scene agents)
  };
}

export interface AgentThinkingEvent extends BaseUIEvent {
  category: 'agent';
  type: 'agent:thinking';
  data: {
    agentId: string;
    thought: string;
    isStreaming: boolean;      // True if more chunks coming
    thoughtIndex?: number;     // For ordering streamed chunks
  };
}

export interface AgentActionEvent extends BaseUIEvent {
  category: 'agent';
  type: 'agent:action';
  data: {
    agentId: string;
    action: AgentAction;
    details?: string;
    progress?: number;         // 0-100 for progress-based actions
  };
}

export interface AgentCompletedEvent extends BaseUIEvent {
  category: 'agent';
  type: 'agent:completed';
  data: {
    agentId: string;
    durationMs: number;
    status: 'success' | 'failed' | 'cancelled';
    result?: string;           // Brief summary of what was accomplished
  };
}

export interface AgentErrorEvent extends BaseUIEvent {
  category: 'agent';
  type: 'agent:error';
  data: {
    agentId: string;
    error: string;
    recoverable: boolean;
    phase: AgentAction;
  };
}

export type AgentEvent =
  | AgentSpawnedEvent
  | AgentThinkingEvent
  | AgentActionEvent
  | AgentCompletedEvent
  | AgentErrorEvent;

// ============================================================================
// Preview Events (for cooking preview visualization)
// ============================================================================

export interface PreviewReadyEvent extends BaseUIEvent {
  category: 'preview';
  type: 'preview:ready';
  data: {
    sceneIndex: number;
    sceneId: string;
    videoPath: string;
    thumbnailPath?: string;    // Optional thumbnail for faster loading
    durationSeconds: number;
  };
}

export interface PreviewAllCompleteEvent extends BaseUIEvent {
  category: 'preview';
  type: 'preview:all_complete';
  data: {
    totalScenes: number;
    scenePaths: Array<{
      sceneIndex: number;
      sceneId: string;
      videoPath: string;
    }>;
    finalVideoPath?: string;   // Path to concatenated final video
  };
}

export interface PreviewErrorEvent extends BaseUIEvent {
  category: 'preview';
  type: 'preview:error';
  data: {
    sceneIndex?: number;
    sceneId?: string;
    error: string;
  };
}

export type PreviewEvent =
  | PreviewReadyEvent
  | PreviewAllCompleteEvent
  | PreviewErrorEvent;

// ============================================================================
// Union Type
// ============================================================================

export type UIEvent = 
  | DirectorEvent
  | SceneEvent
  | EvaluationEvent
  | RenderEvent
  | SystemEvent
  | AgentEvent
  | PreviewEvent;

// ============================================================================
// Event Type Guards
// ============================================================================

export function isDirectorEvent(event: UIEvent): event is DirectorEvent {
  return event.category === 'director';
}

export function isSceneEvent(event: UIEvent): event is SceneEvent {
  return event.category === 'scene';
}

export function isEvaluationEvent(event: UIEvent): event is EvaluationEvent {
  return event.category === 'evaluation';
}

export function isRenderEvent(event: UIEvent): event is RenderEvent {
  return event.category === 'render';
}

export function isSystemEvent(event: UIEvent): event is SystemEvent {
  return event.category === 'system';
}

export function isAgentEvent(event: UIEvent): event is AgentEvent {
  return event.category === 'agent';
}

export function isPreviewEvent(event: UIEvent): event is PreviewEvent {
  return event.category === 'preview';
}

// ============================================================================
// Stream Keys
// ============================================================================

export const STREAM_KEYS = {
  /** Main event stream for all UI events */
  UI_EVENTS: 'ui-events',
  
  /** Per-project event stream */
  projectEvents: (projectId: string) => `ui-events:${projectId}`,
} as const;
