import React from 'react';
import { Composition } from 'remotion';

// Initialize pre-loaded Google Fonts (side-effect import)
import './styles/fonts';

// MainComposition is generated by the workflow - use optional import
let MainComposition: React.FC | null = null;
try {
    // This will be replaced by the actual generated component at runtime
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    MainComposition = require('./generated/scenes/MainComposition').MainComposition;
} catch {
    // No generated composition yet - this is expected on fresh installs
}

// Component test compositions
import { BackgroundTest } from './components/Global/Background';
import { LayoutTest } from './components/Layout/TestComposition';


// Fallback component when no generated composition exists
const FallbackComposition: React.FC = () => (
    <div style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000',
        color: '#fff',
        fontFamily: 'sans-serif'
    }}>
        <p>No generated composition yet. Run the workflow to generate scenes.</p>
    </div>
);

export const RemotionRoot: React.FC = () => {
    // Use MainComposition if available, otherwise fallback
    const CompositionToRender = MainComposition || FallbackComposition;

    return (
        <>
            {/* Legacy composition for backwards compatibility */}
            <Composition
                id="BrandVideo"
                component={CompositionToRender}
                durationInFrames={900}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* New composition ID for the modular workflow */}
            <Composition
                id="GeneratedMainComposition"
                component={CompositionToRender}
                durationInFrames={900}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* 9:16 vertical format for mobile/social */}
            <Composition
                id="GeneratedMainComposition-9x16"
                component={CompositionToRender}
                durationInFrames={900}
                fps={30}
                width={1080}
                height={1920}
            />

            {/* ─── Component Test Compositions ─────────────────────── */}

            {/* Background component test - showcases all presets and layer types */}
            <Composition
                id="BackgroundTest"
                component={BackgroundTest}
                durationInFrames={900}
                fps={30}
                width={1920}
                height={1080}
            />

            {/* Layout component test - BentoGrid with BackgroundRig */}
            <Composition
                id="LayoutTest"
                component={LayoutTest}
                durationInFrames={150}
                fps={30}
                width={1920}
                height={1080}
            />
        </>
    );
};
