import React from 'react';
import { Composition, Still } from 'remotion';
import { BrandVideo } from './compositions/BrandVideo';
import GeneratedVideo from './compositions/GeneratedVideo';
import { BrickPreview } from './compositions/BrickPreview';

// MainComposition is generated by the workflow
import { MainComposition } from './generated/scenes/MainComposition';


// Fallback component when no generated composition exists
const FallbackComposition: React.FC = () => (
    <div style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000',
        color: '#fff',
        fontFamily: 'sans-serif'
    }}>
        <p>No generated composition yet. Run the workflow to generate scenes.</p>
    </div>
);

export const RemotionRoot: React.FC = () => {
    // Use MainComposition if available, otherwise fallback
    const CompositionToRender = MainComposition || FallbackComposition;

    return (
        <>
            {/* Legacy composition for backwards compatibility */}
            <Composition
                id="BrandVideo"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* New composition ID for the modular workflow */}
            <Composition
                id="GeneratedMainComposition"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* 9:16 vertical format for mobile/social */}
            <Composition
                id="GeneratedMainComposition-9x16"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1080}
                height={1920}
            />

            {/* Design System Bricks Preview */}
            <Composition
                id="BrickPreview"
                component={BrickPreview}
                durationInFrames={120}
                fps={30}
                width={1920}
                height={1080}
            />
        </>
    );
};
