import React from 'react';
import { Composition, Still } from 'remotion';
import { BrandVideo } from './compositions/BrandVideo';
import GeneratedVideo from './compositions/GeneratedVideo';

// Try to import MainComposition from generated scenes
// This will be dynamically generated by the workflow
let MainComposition: React.FC | null = null;
try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    MainComposition = require('./generated/scenes/MainComposition').MainComposition;
} catch (e) {
    // MainComposition not yet generated - will use fallback
    console.log('MainComposition not yet generated, using fallback');
}

// Fallback component when no generated composition exists
const FallbackComposition: React.FC = () => (
    <div style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000',
        color: '#fff',
        fontFamily: 'sans-serif'
    }}>
        <p>No generated composition yet. Run the workflow to generate scenes.</p>
    </div>
);

export const RemotionRoot: React.FC = () => {
    // Use MainComposition if available, otherwise fallback
    const CompositionToRender = MainComposition || FallbackComposition;

    return (
        <>
            {/* Legacy composition for backwards compatibility */}
            <Composition
                id="BrandVideo"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* New composition ID for the modular workflow */}
            <Composition
                id="GeneratedMainComposition"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1920}
                height={1080}
            />
            {/* 9:16 vertical format for mobile/social */}
            <Composition
                id="GeneratedMainComposition-9:16"
                component={CompositionToRender}
                durationInFrames={1350}
                fps={30}
                width={1080}
                height={1920}
            />
        </>
    );
};
